[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mona-agent"
version = "0.1.0"
authors = [
    { name = "Your Name" },
]
description = "Mona AI Marketing Agent"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["mona-agent"]